import {
  int, mysqlEnum, mysqlTable, text,
  timestamp, varchar, json, bigint,
} from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: int("id").autoincrement().primaryKey(),
  /** Legacy OAuth identifier — kept for backward compat, nullable for new accounts */
  openId: varchar("openId", { length: 64 }).unique(),
  /** Username: phone number or email address used for login */
  username: varchar("username", { length: 320 }).unique(),
  /** bcrypt hashed password */
  passwordHash: varchar("passwordHash", { length: 255 }),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  plan: mysqlEnum("plan", ["free", "pro", "enterprise"]).default("free").notNull(),
  /** Unique invite code for sharing, auto-generated on first login */
  inviteCode: varchar("inviteCode", { length: 16 }).unique(),
  /** Invited by which user's inviteCode */
  invitedBy: varchar("invitedBy", { length: 16 }),
  /** Credits balance */
  credits: int("credits").default(0).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

// ── File Sessions ─────────────────────────────────────────────────────────────
// Each uploaded file creates a session. Multiple sessions can be merged.

export const sessions = mysqlTable("sessions", {
  id:           varchar("id", { length: 64 }).primaryKey(),
  userId:       int("userId").notNull(),
  filename:     varchar("filename", { length: 255 }).notNull(),
  originalName: varchar("originalName", { length: 255 }).notNull(),
  fileKey:      varchar("fileKey", { length: 512 }),
  fileUrl:      text("fileUrl"),
  fileSizeKb:   int("fileSizeKb"),
  rowCount:     int("rowCount"),
  colCount:     int("colCount"),
  dfInfo:       json("dfInfo"),
  mergedFrom:   json("mergedFrom"),
  isMerged:     int("isMerged").default(0).notNull(),
  /** V3.0: Link to the ResultSet generated by the new pipeline */
  resultSetId:  varchar("resultSetId", { length: 64 }),
  status:       mysqlEnum("status", ["uploading", "ready", "error", "merged"])
                  .default("uploading").notNull(),
  createdAt:    timestamp("createdAt").defaultNow().notNull(),
  updatedAt:    timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Session = typeof sessions.$inferSelect;
export type InsertSession = typeof sessions.$inferInsert;

// ── Reports ───────────────────────────────────────────────────────────────────
// Reports are kept for 24 hours for download, then auto-deleted (no long-term storage)

export const reports = mysqlTable("reports", {
  id:         varchar("id", { length: 64 }).primaryKey(),
  sessionId:  varchar("sessionId", { length: 64 }).notNull(),
  userId:     int("userId").notNull(),
  title:      varchar("title", { length: 255 }).notNull(),
  filename:   varchar("filename", { length: 255 }).notNull(),
  fileKey:    varchar("fileKey", { length: 512 }),
  fileUrl:    text("fileUrl"),
  fileSizeKb: int("fileSizeKb"),
  prompt:     text("prompt"),
  /** Link to the ResultSet that produced this report */
  resultSetId: varchar("resultSetId", { length: 64 }),
  status:     mysqlEnum("status", ["generating", "completed", "failed"])
                .default("generating").notNull(),
  // Auto-expire after 7 days
  expiresAt:  timestamp("expiresAt").notNull(),
  createdAt:  timestamp("createdAt").defaultNow().notNull(),
  updatedAt:  timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Report = typeof reports.$inferSelect;
export type InsertReport = typeof reports.$inferInsert;

// ── ResultSets (V3.0 唯一真值源) ─────────────────────────────────────────────
// 每次计算任务产出一个 ResultSet，包含 8 个可审计字段。
// 页面显示、Excel 导出、IM 回复、AI 表达全部从 ResultSet 读取数字。

export const resultSets = mysqlTable("result_sets", {
  /** 计算任务唯一标识 */
  id:                varchar("id", { length: 64 }).primaryKey(),
  userId:            int("userId").notNull(),
  /** 关联的 session ID（单文件）或 null（多文件合并） */
  sessionId:         varchar("sessionId", { length: 64 }),
  /** 使用的模板 ID（自由对话则为 null） */
  templateId:        varchar("templateId", { length: 64 }),
  /** 计算引擎版本号 */
  computationVersion: varchar("computationVersion", { length: 32 }).notNull(),
  /** 参与计算的源文件列表 JSON */
  sourceFiles:       json("sourceFiles").notNull(),
  /** 应用的筛选条件 JSON */
  filtersApplied:    json("filtersApplied"),
  /** 被跳过的脏数据行数 */
  skippedRowsCount:  int("skippedRowsCount").default(0).notNull(),
  /** 被跳过行的前 5 条示例 JSON */
  skippedRowsSample: json("skippedRowsSample"),
  /** 核心口径计算结果 JSON */
  metrics:           json("metrics").notNull(),
  /** 标准化后的数据行数 */
  rowCount:          int("rowCount").default(0).notNull(),
  /** 标准化后的字段列表 JSON */
  fields:            json("fields"),
  /** 标准化数据行的 S3 存储路径（大数据量不存 DB） */
  dataS3Key:         varchar("dataS3Key", { length: 512 }),
  /** 数据来源平台 */
  sourcePlatform:    varchar("sourcePlatform", { length: 64 }),
  /** 是否为多文件合并结果 */
  isMultiFile:       int("isMultiFile").default(0).notNull(),
  /** 清洗日志 JSON */
  cleaningLog:       json("cleaningLog"),
  /** ResultSet 生成时间（UTC 毫秒时间戳） */
  generatedAt:       bigint("generatedAt", { mode: "number" }).notNull(),
  createdAt:         timestamp("createdAt").defaultNow().notNull(),
});

export type ResultSetRecord = typeof resultSets.$inferSelect;
export type InsertResultSetRecord = typeof resultSets.$inferInsert;

// ── Scheduled Tasks ───────────────────────────────────────────────────────────

export const scheduledTasks = mysqlTable("scheduled_tasks", {
  id:             varchar("id", { length: 64 }).primaryKey(),
  userId:         int("userId").notNull(),
  name:           varchar("name", { length: 255 }).notNull(),
  templatePrompt: text("templatePrompt").notNull(),
  templateName:   varchar("templateName", { length: 100 }),
  cronExpr:       varchar("cronExpr", { length: 100 }).notNull(),
  scheduleDesc:   varchar("scheduleDesc", { length: 100 }),
  notifyEmail:    text("notifyEmail"),
  lastSessionId:  varchar("lastSessionId", { length: 64 }),
  status:         mysqlEnum("status", ["active", "paused", "error"])
                    .default("active").notNull(),
  lastRunAt:      timestamp("lastRunAt"),
  nextRunAt:      timestamp("nextRunAt"),
  lastReportId:   varchar("lastReportId", { length: 64 }),
  runCount:       int("runCount").default(0).notNull(),
  createdAt:      timestamp("createdAt").defaultNow().notNull(),
  updatedAt:      timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type ScheduledTask = typeof scheduledTasks.$inferSelect;
export type InsertScheduledTask = typeof scheduledTasks.$inferInsert;

// ── Invite Records ────────────────────────────────────────────────────────────
// Tracks successful invitations and credit awards

export const inviteRecords = mysqlTable("invite_records", {
  id:            varchar("id", { length: 64 }).primaryKey(),
  inviterUserId: int("inviterUserId").notNull(),
  inviteeUserId: int("inviteeUserId").notNull(),
  inviteCode:    varchar("inviteCode", { length: 16 }).notNull(),
  /** Credits awarded to inviter */
  inviterCredits: int("inviterCredits").default(500).notNull(),
  /** Credits awarded to invitee */
  inviteeCredits: int("inviteeCredits").default(500).notNull(),
  status:        mysqlEnum("status", ["pending", "completed"]).default("completed").notNull(),
  createdAt:     timestamp("createdAt").defaultNow().notNull(),
});

export type InviteRecord = typeof inviteRecords.$inferSelect;
export type InsertInviteRecord = typeof inviteRecords.$inferInsert;

// ── Report Feedback (Self-Learning) ──────────────────────────────────────────
// Users rate reports; high-rated examples are used as RAG few-shot context

export const reportFeedback = mysqlTable("report_feedback", {
  id:         varchar("id", { length: 64 }).primaryKey(),
  reportId:   varchar("reportId", { length: 64 }).notNull(),
  sessionId:  varchar("sessionId", { length: 64 }).notNull(),
  userId:     int("userId").notNull(),
  rating:     int("rating").notNull(), // 1-5 stars
  comment:    text("comment"),
  /** Snapshot of dfInfo columns for similarity matching */
  columnSignature: text("columnSignature"),
  /** The prompt used to generate this report */
  prompt:     text("prompt"),
  /** S3 key of the example data (first 50 rows JSON) */
  exampleDataKey: varchar("exampleDataKey", { length: 512 }),
  createdAt:  timestamp("createdAt").defaultNow().notNull(),
});

export type ReportFeedback = typeof reportFeedback.$inferSelect;
export type InsertReportFeedback = typeof reportFeedback.$inferInsert;
// ── HR: Payslip Records ────────────────────────────────────────────────────────
// Each payslip generation batch creates one record

export const hrPayslipRecords = mysqlTable("hr_payslip_records", {
  id:             varchar("id", { length: 64 }).primaryKey(),
  userId:         int("userId").notNull(),
  filename:       varchar("filename", { length: 255 }).notNull(),
  fileKey:        varchar("fileKey", { length: 512 }),
  fileUrl:        text("fileUrl"),
  fileSizeKb:     int("fileSizeKb"),
  employeeCount:  int("employeeCount"),
  period:         varchar("period", { length: 20 }),   // e.g. "2024-03"
  /** JSON: { nameCol, emailCol, baseSalaryCol, bonusCol, deductionCol, insuranceCol } */
  fieldMap:       json("fieldMap"),
  /** JSON: { totalPayroll, avgSalary, totalTax, totalNetPay } */
  summary:        json("summary"),
  reportFileKey:  varchar("reportFileKey", { length: 512 }),
  reportFileUrl:  text("reportFileUrl"),
  emailStatus:    varchar("emailStatus", { length: 20 }),  // null | 'sending' | 'done' | 'partial'
  emailSentCount: int("emailSentCount").default(0),
  expiresAt:      timestamp("expiresAt").notNull(),  // Auto-expire after 7 days
  status:         mysqlEnum("status", ["generating", "ready", "error"]).default("generating").notNull(),
  createdAt:      timestamp("createdAt").defaultNow().notNull(),
  updatedAt:      timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type HrPayslipRecord = typeof hrPayslipRecords.$inferSelect;
export type InsertHrPayslipRecord = typeof hrPayslipRecords.$inferInsert;

// ── HR: Attendance Sessions ────────────────────────────────────────────────────
// Each attendance analysis creates one record

export const hrAttendanceSessions = mysqlTable("hr_attendance_sessions", {
  id:             varchar("id", { length: 64 }).primaryKey(),
  userId:         int("userId").notNull(),
  filename:       varchar("filename", { length: 255 }).notNull(),
  fileKey:        varchar("fileKey", { length: 512 }),
  fileUrl:        text("fileUrl"),
  fileSizeKb:     int("fileSizeKb"),
  rowCount:       int("rowCount"),
  period:         varchar("period", { length: 20 }),   // e.g. "2024-03"
  /** JSON: { nameCol, dateCol, checkInCol, checkOutCol, deptCol } */
  fieldMap:       json("fieldMap"),
  /** JSON: { totalEmployees, attendanceRate, lateCount, absentCount, overtimeHours } */
  summary:        json("summary"),
  reportFileKey:  varchar("reportFileKey", { length: 512 }),
  reportFileUrl:  text("reportFileUrl"),
  status:         mysqlEnum("status", ["analyzing", "ready", "error"]).default("analyzing").notNull(),
  createdAt:      timestamp("createdAt").defaultNow().notNull(),
  updatedAt:      timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type HrAttendanceSession = typeof hrAttendanceSessions.$inferSelect;
export type InsertHrAttendanceSession = typeof hrAttendanceSessions.$inferInsert;

// ── OpenClaw Tasks (Polling Architecture) ─────────────────────────────────────
// Tasks created when users send messages with files; polled by OpenClaw agent

export const openclawTasks = mysqlTable("openclaw_tasks", {
  id:          varchar("id", { length: 64 }).primaryKey(),
  userId:      int("userId").notNull(),
  /** External user identifier passed to OpenClaw */
  externalUserId: varchar("externalUserId", { length: 128 }),
  message:     text("message").notNull(),
  /** JSON array of S3 presigned URLs */
  fileUrls:    json("fileUrls").$type<string[]>(),
  /** JSON array of original file names */
  fileNames:   json("fileNames").$type<string[]>(),
  /** Reply text returned by OpenClaw */
  reply:       text("reply"),
  /** JSON array of output files: { name, fileKey, fileUrl, mimeType } */
  outputFiles: json("outputFiles").$type<Array<{ name: string; fileKey: string; fileUrl: string; mimeType: string }>>(),
  status:      mysqlEnum("status", ["pending", "processing", "completed", "failed"])
                 .default("pending").notNull(),
  /** Milliseconds since epoch when task was picked up by OpenClaw */
  pickedUpAt:  timestamp("pickedUpAt"),
  /** Milliseconds since epoch when task was completed */
  completedAt: timestamp("completedAt"),
  createdAt:   timestamp("createdAt").defaultNow().notNull(),
  updatedAt:   timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type OpenclawTask = typeof openclawTasks.$inferSelect;
export type InsertOpenclawTask = typeof openclawTasks.$inferInsert;

// ── Message Feedback ───────────────────────────────────────────────────────────────────────────────────────
// Users rate individual AI messages (👍/👎) with optional comment
export const messageFeedback = mysqlTable("message_feedback", {
  id:        varchar("id", { length: 64 }).primaryKey(),
  userId:    int("userId"),
  /** The message content being rated (first 500 chars for reference) */
  messagePreview: varchar("messagePreview", { length: 500 }),
  /** 1 = thumbs up, -1 = thumbs down */
  rating:    int("rating").notNull(),
  /** Optional user comment */
  comment:   text("comment"),
  /** Page/context where feedback was given */
  context:   varchar("context", { length: 128 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type MessageFeedback = typeof messageFeedback.$inferSelect;
export type InsertMessageFeedback = typeof messageFeedback.$inferInsert;

// ── Admin API Keys ─────────────────────────────────────────────────────────────
// API keys for external systems (e.g. OpenClaw) to access admin REST endpoints
export const adminApiKeys = mysqlTable("admin_api_keys", {
  id:         int("id").autoincrement().primaryKey(),
  name:       varchar("name", { length: 128 }).notNull(),
  keyHash:    varchar("keyHash", { length: 128 }).notNull().unique(),
  keyPrefix:  varchar("keyPrefix", { length: 20 }).notNull(),
  isActive:   int("isActive").default(1).notNull(),
  lastUsedAt: timestamp("lastUsedAt"),
  createdAt:  timestamp("createdAt").defaultNow().notNull(),
});
export type AdminApiKey = typeof adminApiKeys.$inferSelect;
export type InsertAdminApiKey = typeof adminApiKeys.$inferInsert;

// ── IM: Conversations ─────────────────────────────────────────────────────────
// A conversation is either a 1v1 direct message or an AI assistant chat

export const imConversations = mysqlTable("im_conversations", {
  id:        varchar("id", { length: 64 }).primaryKey(),
  /** 'direct' = 1v1 between two users, 'ai' = user with AI assistant */
  type:      mysqlEnum("type", ["direct", "ai"]).notNull(),
  /** Last message preview for conversation list */
  lastMessage: text("lastMessage"),
  lastMessageAt: timestamp("lastMessageAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type ImConversation = typeof imConversations.$inferSelect;
export type InsertImConversation = typeof imConversations.$inferInsert;

// ── IM: Participants ───────────────────────────────────────────────────────────
// Maps users to conversations (many-to-many)

export const imParticipants = mysqlTable("im_participants", {
  id:             int("id").autoincrement().primaryKey(),
  conversationId: varchar("conversationId", { length: 64 }).notNull(),
  userId:         int("userId").notNull(),
  /** Unread message count for this user in this conversation */
  unreadCount:    int("unreadCount").default(0).notNull(),
  createdAt:      timestamp("createdAt").defaultNow().notNull(),
});

export type ImParticipant = typeof imParticipants.$inferSelect;
export type InsertImParticipant = typeof imParticipants.$inferInsert;

// ── IM: Messages ──────────────────────────────────────────────────────────────
// Individual messages within a conversation

export const imMessages = mysqlTable("im_messages", {
  id:             varchar("id", { length: 64 }).primaryKey(),
  conversationId: varchar("conversationId", { length: 64 }).notNull(),
  /** 0 = AI assistant, positive int = user id */
  senderId:       int("senderId").notNull(),
  senderName:     varchar("senderName", { length: 128 }),
  /** Message type: text, file, ai_thinking */
  type:           mysqlEnum("type", ["text", "file", "ai_thinking"]).default("text").notNull(),
  content:        text("content").notNull(),
  /** For file messages: JSON { name, url, size } */
  fileInfo:       json("fileInfo"),
  createdAt:      timestamp("createdAt").defaultNow().notNull(),
});

export type ImMessage = typeof imMessages.$inferSelect;
export type InsertImMessage = typeof imMessages.$inferInsert;

// ── Personal Templates (V13.7) ─────────────────────────────────────────────────
// Users can save calculation rules as reusable templates
// e.g. "RUSIN multi-level pricing template": input cost price → auto-calculate all tier prices

export const personalTemplates = mysqlTable("personal_templates", {
  id:          varchar("id", { length: 64 }).primaryKey(),
  userId:      int("userId").notNull(),
  /** Display name of the template */
  name:        varchar("name", { length: 255 }).notNull(),
  /** Short description of what this template does */
  description: text("description"),
  /** Category: pricing | payroll | attendance | sales | custom */
  category:    varchar("category", { length: 64 }).default("custom").notNull(),
  /** The full conversation context / calculation rules as a system prompt */
  systemPrompt: text("systemPrompt").notNull(),
  /** JSON: list of required input fields, e.g. [{ key: "costPrice", label: "供货价", type: "number", unit: "元" }] */
  inputFields: json("inputFields").$type<Array<{ key: string; label: string; type: string; unit?: string }>>(),
  /** JSON: example output preview (first result) */
  exampleOutput: json("exampleOutput"),
  /** How many times this template has been used */
  useCount:    int("useCount").default(0).notNull(),
  /** Last time this template was used */
  lastUsedAt:  timestamp("lastUsedAt"),
  createdAt:   timestamp("createdAt").defaultNow().notNull(),
  updatedAt:   timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type PersonalTemplate = typeof personalTemplates.$inferSelect;
export type InsertPersonalTemplate = typeof personalTemplates.$inferInsert;

// ── Chat Conversations (V13.9 对话持久化) ──────────────────────────────────────
// Each user's ATLAS chat session is a conversation. A new conversation is created
// when the user starts a fresh chat. Messages are appended as the conversation progresses.

export const chatConversations = mysqlTable("chat_conversations", {
  id:          varchar("id", { length: 64 }).primaryKey(),
  /** 0 = anonymous visitor */
  userId:      int("userId").default(0).notNull(),
  /** Optional: the file session IDs attached to this conversation */
  sessionIds:  json("sessionIds").$type<string[]>(),
  /** Short preview of the first user message */
  title:       varchar("title", { length: 255 }),
  /** Total number of messages in this conversation */
  messageCount: int("messageCount").default(0).notNull(),
  createdAt:   timestamp("createdAt").defaultNow().notNull(),
  updatedAt:   timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type ChatConversation = typeof chatConversations.$inferSelect;
export type InsertChatConversation = typeof chatConversations.$inferInsert;

// ── Chat Messages (V13.9 对话持久化) ──────────────────────────────────────────
// Individual messages within a chat conversation.

export const chatMessages = mysqlTable("chat_messages", {
  id:             varchar("id", { length: 64 }).primaryKey(),
  conversationId: varchar("conversationId", { length: 64 }).notNull(),
  /** 'user' or 'assistant' */
  role:           mysqlEnum("role", ["user", "assistant"]).notNull(),
  content:        text("content").notNull(),
  /** Optional: file names attached to this message */
  fileNames:      json("fileNames").$type<string[]>(),
  /** Token count estimate (for cost tracking) */
  tokenEstimate:  int("tokenEstimate"),
  createdAt:      timestamp("createdAt").defaultNow().notNull(),
});

export type ChatMessage = typeof chatMessages.$inferSelect;
export type InsertChatMessage = typeof chatMessages.$inferInsert;

// ── Bots (机器人系统) ──────────────────────────────────────────────────────────
// Admin 创建的机器人，类似飞书机器人。每个机器人有唯一 Token，
// 外部服务（如 OpenClaw）用此 Token 调用 ATLAS API 收发消息。
export const bots = mysqlTable("bots", {
  id:          varchar("id", { length: 64 }).primaryKey(),
  /** 机器人名称，如"小虾米" */
  name:        varchar("name", { length: 128 }).notNull(),
  /** 机器人描述 */
  description: text("description"),
  /** 机器人头像 emoji 或 URL */
  avatar:      varchar("avatar", { length: 255 }).default("🤖"),
  /** 唯一 Token，外部服务用此鉴权调用 ATLAS API */
  token:       varchar("token", { length: 128 }).unique().notNull(),
  /** 外部服务的 Webhook URL，ATLAS 将用户消息推送到此地址 */
  webhookUrl:  text("webhookUrl"),
  /** 是否启用 */
  enabled:     int("enabled").default(1).notNull(),
  /** 创建者 userId */
  createdBy:   int("createdBy").notNull(),
  createdAt:   timestamp("createdAt").defaultNow().notNull(),
  updatedAt:   timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type Bot = typeof bots.$inferSelect;
export type InsertBot = typeof bots.$inferInsert;

// ── Bot Messages (机器人消息) ──────────────────────────────────────────────────
// 用户与机器人之间的消息记录
export const botMessages = mysqlTable("bot_messages", {
  id:        varchar("id", { length: 64 }).primaryKey(),
  botId:     varchar("botId", { length: 64 }).notNull(),
  userId:    int("userId").notNull(),
  /** 'user' = 用户发的，'bot' = 机器人回复的 */
  role:      mysqlEnum("role", ["user", "bot"]).notNull(),
  content:   text("content").notNull(),
  /** 外部消息ID，用于幂等去重 */
  externalId: varchar("externalId", { length: 128 }),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type BotMessage = typeof botMessages.$inferSelect;
export type InsertBotMessage = typeof botMessages.$inferInsert;
